#!/bin/bash
# request Bourne again shell as shell for job
#$ -S /bin/bash
# merge stderr with stdout
#$ -j y
# assign a name to submitted job
#$ -N movie
# change output file name
#$ -o $HOME/output/$JOB_NAME.$JOB_ID
# export environment variables
#$ -V

export DISPLAY=:1

echo $HOSTNAME
cd $PETSC_TMP
rm movie.mp4 img0* 
renumber.sh
png2movie.sh

MOVIEFILE=`basename $PETSC_TMP`
DATE=`date '+%F'`
cp movie.mp4 /nas-0-0/abergman/movies/$DATE.$MOVIEFILE.mp4
